services:
  price-pusher:
    # Use this to build the price pusher from source.
    #
    # Please note that the docker build from source only works in x86_64 platforms
    # and doesn't work on arm platforms (like Apple M1/M2).
    #
    # build:
    #   context: ../..
    #   dockerfile: Dockerfile.node
    #   args:
    #     package: "@pythnetwork/price-pusher"

    # Replace <version> with the latest released image of the price pusher from here:
    # https://gallery.ecr.aws/pyth-network/xc-price-pusher
    image: public.ecr.aws/pyth-network/xc-price-pusher:v6.8.0
    restart: always
    command:
      - "--"
      - "evm"
      - "--endpoint"
      # Replace this with RPC endpoint URL for the EVM network.
      - "https://klaytn-pokt.nodies.app"
      - "--mnemonic-file"
      - "/mnemonic"
      # Replace this with the address of the Pyth contract on the EVM network.
      - "--pyth-contract-address"
      - "0x2880ab155794e7179c9ee2e38200202908c17b43"
      - "--price-service-endpoint"
      - "https://hermes.pyth.network" # Replace this with a private Hermes RPC for more reliability
      - "--price-config-file"
      - "/price_config"
    configs:
      - mnemonic
      - price_config
configs:
  mnemonic:
    file: /home/teko/data/x-team/pyth/mnemonic.txt # Replace this with the path to the mnemonic file
  price_config:
    file: /home/teko/data/x-team/pyth/price-config.yaml # Replace this with the path to the price configuration file
